config/routes.rb
Rails.application.routes.draw do
  
  get '/events' => 'events#index'
  get 'events/details'
  post 'events/create'
  delete 'events/destroy'

  devise_for :users
  root to: 'home#index'
  
  get '/about/college'      => 'home#about_college'
  get '/about/anugoonj'     => 'home#about_anugoonj'
  get '/about/dexterous'    => 'home#about_dexterous'
  get '/about/coordinators' => 'home#coordinators'
  get '/contact_us'         => 'home#contact_us'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:full_name, :college, :contact_no, :gender, :year, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:full_name, :college, :contact_no, :gender, :year, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def details
    unless Event.find_by(name: params[:event]) == nil
      @event = Event.find_by(name: params[:event])
    else
      redirect_to events_path, alert: 'Could not find event!'
    end
  end

  def create
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_college
  end

  def about_anugoonj
  end

  def about_dexterous
  end

  def coordinators
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_card.html.haml
.col-sm-6.col-md-4
  .well
    %h4
      %span.label.label-success.pull-right= event.family
    %h3
      = event.title
      %br/
      %small= event.name.humanize
    %p.text-justify= truncate(event.description, length: 75, separator: ' ') { link_to "read more", events_details_path(event: event.name) }
    %p
      %b Registration fees:
      = event.reg_fees
    %p.text-right
      /
        = link_to "Register", "#", class: 'btn btn-primary'
      = link_to "Details", events_details_path(event: event.name), class: 'btn btn-default'

app/views/events/create.html.haml
%h1 Events#create
%p Find me in app/views/events/create.html.haml

app/views/events/destroy.html.haml
%h1 Events#destroy
%p Find me in app/views/events/destroy.html.haml

app/views/events/details.html.haml
.col-md-2
.col-md-8
  .well
    %h4
      %span.label.label-success.pull-right= @event.family
    %h3
      = @event.title
      %br/
      %small= @event.name.humanize
    %p= @event.description
    %p
      %b Venue:
      = @event.location
    %p
      %b Registration fees:
      = @event.reg_fees
    %p
      %b Winning prize:
      = @event.win_prize
    %p
      %b Runner-up prize:
      = @event.run_prize
    %p
      %b Rules:
      = h @event.rules.html_safe

app/views/events/index.html.haml
- @events.each do |event|
  = render partial: "card", locals: { event: event }
  - if event.id % 3 == 0
    .row

app/views/home/about_anugoonj.html.haml
.well
  %h1 About Anugoonj
  %p We're under construction. Please come back later!

app/views/home/about_college.html.haml
.well
  %h1 Roorkee Institute of Technology, Roorkee
  %p We're under construction. Please come back later!

app/views/home/about_dexterous.html.haml
.well
  %h1 About Dexterous
  %p We're under construction. Please come back later!

app/views/home/contact_us.html.haml
.well
  %h1 Contact us
  %p We're under construction. Please come back later!

app/views/home/coordinators.html.haml
.well
  %h1 Organizing team
  %p We're under construction. Please come back later!

app/views/home/index.html.haml
.jumbotron
  %h1 Welcome to Anugoonj 2016 official site!
  %p
    Numerous events, and one big fest.
    = link_to "Explore the events now!", events_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Anugoonj"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Anugoonj", root_path, class: "navbar-brand"
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Events", events_path
            - if user_signed_in?
              %li
                .navbar-text
                  Signed in as
                  = link_to current_user.full_name, edit_user_registration_path, class: "navbar-link"
              %li= link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Login", new_user_session_path
              %li= link_to "Register", new_user_registration_path
            /  
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: ""}
                  About
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "Anugoonj", about_anugoonj_path
                  %li= link_to "College", about_college_path
                  %li= link_to "Coordinators", about_coordinators_path

    %nav#loading.navbar.navbar-default.navbar-fixed-bottom{role: "navigation", style: "display: none;"}
      %center
        %p.navbar-text The page is loading. This might take a few seconds depending on your internet speed...

    .container-fluid
      .row
        .col-lg-12
          = bootstrap_flash
          = yield